package com.yf.psp.db.postgres.csm;

import java.util.Date;

public class TblCsmUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.delete_flag
     *
     * @mbggenerated
     */
    private Short deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.contact_no
     *
     * @mbggenerated
     */
    private String contactNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.identity_no
     *
     * @mbggenerated
     */
    private String identityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_csm_user.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.user_id
     *
     * @return the value of tbl_csm_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.user_id
     *
     * @param userId the value for tbl_csm_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.user_name
     *
     * @return the value of tbl_csm_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.user_name
     *
     * @param userName the value for tbl_csm_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.password
     *
     * @return the value of tbl_csm_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.password
     *
     * @param password the value for tbl_csm_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.tenant_id
     *
     * @return the value of tbl_csm_user.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.tenant_id
     *
     * @param tenantId the value for tbl_csm_user.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.role_name
     *
     * @return the value of tbl_csm_user.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.role_name
     *
     * @param roleName the value for tbl_csm_user.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.delete_flag
     *
     * @return the value of tbl_csm_user.delete_flag
     *
     * @mbggenerated
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.delete_flag
     *
     * @param deleteFlag the value for tbl_csm_user.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.delete_time
     *
     * @return the value of tbl_csm_user.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.delete_time
     *
     * @param deleteTime the value for tbl_csm_user.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.create_time
     *
     * @return the value of tbl_csm_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.create_time
     *
     * @param createTime the value for tbl_csm_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.real_name
     *
     * @return the value of tbl_csm_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.real_name
     *
     * @param realName the value for tbl_csm_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.company_id
     *
     * @return the value of tbl_csm_user.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.company_id
     *
     * @param companyId the value for tbl_csm_user.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.contact_no
     *
     * @return the value of tbl_csm_user.contact_no
     *
     * @mbggenerated
     */
    public String getContactNo() {
        return contactNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.contact_no
     *
     * @param contactNo the value for tbl_csm_user.contact_no
     *
     * @mbggenerated
     */
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo == null ? null : contactNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.identity_no
     *
     * @return the value of tbl_csm_user.identity_no
     *
     * @mbggenerated
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.identity_no
     *
     * @param identityNo the value for tbl_csm_user.identity_no
     *
     * @mbggenerated
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo == null ? null : identityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_csm_user.status
     *
     * @return the value of tbl_csm_user.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_csm_user.status
     *
     * @param status the value for tbl_csm_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}