package com.yf.psp.db.postgres.csm.dao;

import com.yf.psp.db.postgres.csm.TblCsmUser;

public interface TblCsmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    int insert(TblCsmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    int insertSelective(TblCsmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    TblCsmUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCsmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_csm_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCsmUser record);
}