package com.yf.psp.db.postgres.rbac;


 
import java.util.HashMap; 
import java.util.Map;
import java.util.Set;
 

/**
 * Model class of 角色表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RbacRole  {
	//系统级角色在此定义常量
	public static class RoleName{
		public static final String TENANT_GLOBAL_ADMIN = "tenantGlobalAdmin";
		public static final String TENANT_APP_ADMIN = "tenantAppAdmin";
		public static final String TENANT_NORMAL_USER  = "tenantNormalUser";
	}
	public static class RoleType{
		/* 
		1:普通角色
		2:行政角色
		3:积分类角色
		*/
		public static final Integer NORMAL = 1;
		public static final Integer  ADMINISTRATION  = 2;
		public static final Integer  GRADE  = 3;
		
	}
	/** serialVersionUID. */
	//private static final long serialVersionUID = 1L;

	/** 继承角色id. */
	private String inheritRoleName;

	/** 上级角色id. */
	private String superiorRoleName;

	/** 角色类型. */
	private Integer roleType;

	 

	/** be_inherited_type. */
	private Short beInheritedType;

	/** role_name. */
	private String roleName;

	private String homePageUrl;

 
	private Map<Integer/*role_mutex_id*/,Set<String>/*role_name*/> roleMutex = new HashMap<>();

	 
	private Map<Integer/*resId*/,RbacPrivilege>  resIdPrivileges = new HashMap<>();
	private Map<Integer/*resType*/,Map<String/*resource*/,RbacPrivilege>>  privileges = new HashMap<>();


	private Short deleteFlag; 

	public Short getDeleteFlag() {
		return deleteFlag;
	}

	public void setDeleteFlag(Short deleteFlag) {
		this.deleteFlag = deleteFlag;
	}


	public String getHomePageUrl() {
		return homePageUrl;
	}

	public void setHomePageUrl(String homePageUrl) {
		this.homePageUrl = homePageUrl;
	}

	/**
	 * Set the 继承角色id.
	 * 
	 * @param inheritRoleName
	 *            继承角色id
	 */
	public void setInheritRoleName(String inheritRoleName) {
		this.inheritRoleName = inheritRoleName;
	}

	/**
	 * Get the 继承角色id.
	 * 
	 * @return 继承角色id
	 */
	public String getInheritRoleName() {
		return this.inheritRoleName;
	}

	/**
	 * Set the 上级角色id.
	 * 
	 * @param superiorRoleName
	 *            上级角色id
	 */
	public void setSuperiorRoleName(String superiorRoleName) {
		this.superiorRoleName = superiorRoleName;
	}

	/**
	 * Get the 上级角色id.
	 * 
	 * @return 上级角色id
	 */
	public String getSuperiorRoleName() {
		return this.superiorRoleName;
	}

	/**
	 * Set the 角色类型.
	 * 
	 * @param roleType
	 *            角色类型
	 */
	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	/**
	 * Get the 角色类型.
	 * 
	 * @return 角色类型
	 */
	public Integer getRoleType() {
		return this.roleType;
	}

	  

	/**
	 * Set the be_inherited_type.
	 * 
	 * @param beInheritedType
	 *            be_inherited_type
	 */
	public void setBeInheritedType(Short beInheritedType) {
		this.beInheritedType = beInheritedType;
	}

	/**
	 * Get the be_inherited_type.
	 * 
	 * @return be_inherited_type
	 */
	public Short getBeInheritedType() {
		return this.beInheritedType;
	}

	/**
	 * Set the role_name.
	 * 
	 * @param roleName
	 *            role_name
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * Get the role_name.
	 * 
	 * @return role_name
	 */
	public String getRoleName() {
		return this.roleName;
	}

	public Map<Integer, Set<String>> getRoleMutex() {
		return roleMutex;
	}

	public void setRoleMutex(Map<Integer, Set<String>> roleMutex) {
		this.roleMutex = roleMutex;
	}

	public Map<Integer, Map<String, RbacPrivilege>> getPrivileges() {
		return privileges;
	}

	public void setPrivileges(Map<Integer, Map<String, RbacPrivilege>> privileges) {
		this.privileges = privileges;
	}

	
 
	public Map<Integer, RbacPrivilege> getResIdPrivileges() {
		return resIdPrivileges;
	}

	public void setResIdPrivileges(Map<Integer, RbacPrivilege> resIdPrivileges) {
		this.resIdPrivileges = resIdPrivileges;
	}

	public void addOneResource(Integer resType,RbacPrivilege privilege) {
		Map<String/*resource*/,RbacPrivilege> p = this.privileges.get(resType);
		if(p==null) {
			p = new HashMap<>();
			this.privileges.put(resType, p);
		}
		p.put(privilege.getRbacResource().getRes(), privilege);
	}
	 
	public RbacPrivilege findResource(Integer resType,String resource) {
		Map<String/*resource*/,RbacPrivilege> p = this.privileges.get(resType);
		if(p==null) {
			return null;
		}
		return p.get(resource);
	}
}
