package com.yf.psp.db.postgres.rbac;


import java.sql.Timestamp;

/**
 * Model class of tbl_rbac_role_mutex.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RbacRoleMutex  {

	/** serialVersionUID. */
	//private static final long serialVersionUID = 1L;

	/** role_mutex_id. */
	private Integer roleMutexId;

	 
	/** 角色表. */
	private String roleName;
	private Short deleteFlag; 

	public Short getDeleteFlag() {
		return deleteFlag;
	}

	public void setDeleteFlag(Short deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
	/**
	 * Constructor.
	 */
	public RbacRoleMutex() {
	}

	/**
	 * Set the role_mutex_id.
	 * 
	 * @param roleMutexId
	 *            role_mutex_id
	 */
	public void setRoleMutexId(Integer roleMutexId) {
		this.roleMutexId = roleMutexId;
	}

	/**
	 * Get the role_mutex_id.
	 * 
	 * @return role_mutex_id
	 */
	public Integer getRoleMutexId() {
		return this.roleMutexId;
	}

	 

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	
}
