package com.yf.psp.db.postgres.company.dao;

import com.yf.psp.db.postgres.company.TblCompanyLabelRela;


public interface TblCompanyLabelRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer relaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    int insert(TblCompanyLabelRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    int insertSelective(TblCompanyLabelRela record);
    int deleteByCompanyId(Integer companyId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    TblCompanyLabelRela selectByPrimaryKey(Integer relaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCompanyLabelRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_label_rela
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCompanyLabelRela record);
}