package com.yf.psp.db.postgres.company.dao;

import com.yf.psp.db.postgres.company.TblCompanyChangeLog;


public interface TblCompanyChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    int insert(TblCompanyChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    int insertSelective(TblCompanyChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    TblCompanyChangeLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCompanyChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company_change_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCompanyChangeLog record);
}