package com.yf.psp.db.postgres.company;

import java.util.Date;

public class TblCompanyLabelRela {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label_rela.rela_id
     *
     * @mbggenerated
     */
    private Integer relaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label_rela.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label_rela.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label_rela.delete_flag
     *
     * @mbggenerated
     */
    private Short deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label_rela.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label_rela.rela_id
     *
     * @return the value of tbl_company_label_rela.rela_id
     *
     * @mbggenerated
     */
    public Integer getRelaId() {
        return relaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label_rela.rela_id
     *
     * @param relaId the value for tbl_company_label_rela.rela_id
     *
     * @mbggenerated
     */
    public void setRelaId(Integer relaId) {
        this.relaId = relaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label_rela.company_id
     *
     * @return the value of tbl_company_label_rela.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label_rela.company_id
     *
     * @param companyId the value for tbl_company_label_rela.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label_rela.label_id
     *
     * @return the value of tbl_company_label_rela.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label_rela.label_id
     *
     * @param labelId the value for tbl_company_label_rela.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label_rela.delete_flag
     *
     * @return the value of tbl_company_label_rela.delete_flag
     *
     * @mbggenerated
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label_rela.delete_flag
     *
     * @param deleteFlag the value for tbl_company_label_rela.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label_rela.delete_time
     *
     * @return the value of tbl_company_label_rela.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label_rela.delete_time
     *
     * @param deleteTime the value for tbl_company_label_rela.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}