package com.yf.psp.db.postgres.company;

public class TblCompanyLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label.label_id
     *
     * @mbggenerated
     */
    private Long labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label.label_name
     *
     * @mbggenerated
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_company_label.label_type
     *
     * @mbggenerated
     */
    private Short labelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label.label_id
     *
     * @return the value of tbl_company_label.label_id
     *
     * @mbggenerated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label.label_id
     *
     * @param labelId the value for tbl_company_label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label.label_name
     *
     * @return the value of tbl_company_label.label_name
     *
     * @mbggenerated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label.label_name
     *
     * @param labelName the value for tbl_company_label.label_name
     *
     * @mbggenerated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_company_label.label_type
     *
     * @return the value of tbl_company_label.label_type
     *
     * @mbggenerated
     */
    public Short getLabelType() {
        return labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_company_label.label_type
     *
     * @param labelType the value for tbl_company_label.label_type
     *
     * @mbggenerated
     */
    public void setLabelType(Short labelType) {
        this.labelType = labelType;
    }
}